"""
PEGASUS OS — Market Analysis Agent

Capabilities:
- Market data monitoring
- News and trend analysis
- Data correlation
- Report generation
- Alert detection
- Historical analysis

Desktop integration:
- Opens Browser for market data
- Opens Terminal for data processing
- Opens Files for report storage

Note: Any financial functionality must be clearly presented as
analysis/information rather than guaranteed financial advice.
"""

import logging
from typing import Any

from .base import BaseAgent

logger = logging.getLogger("pegasus.agents.market")


class MarketAnalysisAgent(BaseAgent):
    """
    Marketing & Market Analysis Agent specializes in documentation, README, release notes,
    and market/product content.
    """

    def __init__(self):
        super().__init__(name="Marketing Agent")

    def can_handle(self, task_description: str) -> bool:
        """Marketing agent handles readme, docs, release notes, marketing, and analysis tasks."""
        keywords = [
            "marketing", "readme", "documentation", "release notes", "changelog",
            "market", "trend", "analysis", "report", "stock",
            "price", "competitor", "industry", "forecast",
            "revenue", "growth", "investment", "financial"
        ]
        return any(kw in task_description.lower() for kw in keywords)

    async def execute(self, step: Any, tools: dict[str, Any], context: Any) -> str:
        """Execute a market analysis step."""
        task = step.name
        logger.info(f"[Market] Executing: {task}")

        browser = self._use_tool(tools, "browser")
        terminal = self._use_tool(tools, "terminal")
        filesystem = self._use_tool(tools, "filesystem")

        # Search for market data
        sources = []
        if browser:
            search_results = await browser.search(task)
            sources = search_results.get("results", [])
            logger.info(f"[Market] Found {len(sources)} sources")

        # Extract information
        extracted_info = []
        if browser and sources:
            for source in sources[:5]:
                try:
                    content = await browser.extract(source.get("url", ""))
                    if content:
                        extracted_info.append({
                            "title": source.get("title", ""),
                            "url": source.get("url", ""),
                            "snippet": source.get("snippet", ""),
                            "content_length": len(content),
                        })
                except Exception as e:
                    logger.warning(f"[Market] Failed to extract: {e}")

        # Generate analysis
        analysis = await self._analyze_market(task, extracted_info)

        # Save report if filesystem available
        if filesystem:
            report = f"# Market Analysis: {task}\n\n{analysis}\n\n---\n*Generated by PEGASUS Market Analysis Agent*\n*This analysis is for informational purposes only and does not constitute financial advice.*"
            await filesystem.write_file(
                f"market_analysis_{task[:30].replace(' ', '_')}.md",
                report
            )

        return analysis

    async def _analyze_market(self, topic: str, sources: list[dict]) -> str:
        """Generate a market analysis from collected data."""
        if not sources:
            return f"No market data found for: {topic}"

        source_text = "\n".join([
            f"- {s.get('title', 'Untitled')}: {s.get('snippet', 'No snippet')}"
            for s in sources
        ])

        prompt = f"""Market analysis topic: {topic}

Data sources found:
{source_text}

Provide a concise market analysis including:
1. Current market state
2. Key trends identified
3. Relevant factors
4. Potential implications
5. Key takeaways

Important: This analysis is for informational purposes only.
Do not present any information as guaranteed financial advice."""

        analysis = await self._llm_call(
            system_prompt="""You are a market analyst.
Provide clear, factual market analysis based on available data.
Always include a disclaimer that this is for informational purposes only.
Be objective and data-driven.""",
            user_prompt=prompt
        )

        return analysis if analysis else f"Could not generate analysis for: {topic}"
